name: "Run Jest Tests"

# Trigger the workflow on merge of pull request or direct push,
# but only for the main branch
on:
  pull_request :
    types: [ opened, edited, synchronize, reopened]

jobs:
  tests:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci
      - run: npm run test
      - run: npm run test:coverage
